"""add is_public to recipes

Revision ID: 7b42b42115dd
Revises: d03ef81d7de7
Create Date: 2026-01-03 22:20:48.865044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b42b42115dd'
down_revision: Union[str, Sequence[str], None] = 'd03ef81d7de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add column as nullable
    op.add_column('recipes', sa.Column('is_public', sa.Boolean(), nullable=True))
    
    # 2. Set default value for existing rows
    op.execute("UPDATE recipes SET is_public = true")
    
    # 3. Alter column to be NOT NULL
    op.alter_column('recipes', 'is_public', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'is_public')
    # ### end Alembic commands ###
