"""add_security_notifications_field

Revision ID: 8613537b803a
Revises: 3e125208b901
Create Date: 2026-01-09 20:43:59.740845

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8613537b803a"
down_revision: Union[str, Sequence[str], None] = "3e125208b901"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "security_notifications_enabled",
            sa.Boolean(),
            nullable=False,
            server_default="true",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "security_notifications_enabled")
    # ### end Alembic commands ###
