"""Initial migration

Revision ID: cbb4e747c986
Revises: 
Create Date: 2026-01-01 23:56:15.507964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbb4e747c986'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_cache',
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('prompt_version', sa.String(length=10), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('raw_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('video_id', 'prompt_version', 'model')
    )
    op.create_index(op.f('ix_extraction_cache_expires_at'), 'extraction_cache', ['expires_at'], unique=False)
    
    # Re-creating recipes table to handle ID type change cleanly
    op.drop_table('recipes')
    op.create_table('recipes',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('source_url', sa.Text(), nullable=False),
        sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('thumbnail_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('recipes', sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('recipes', sa.Column('steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('recipes', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('recipes', sa.Column('ingredients', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.create_foreign_key(op.f('recipes_owner_id_fkey'), 'recipes', 'users', ['owner_id'], ['id'])
    op.create_index(op.f('ix_recipes_title'), 'recipes', ['title'], unique=False)
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    op.alter_column('recipes', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('recipes', 'data')
    op.drop_column('recipes', 'source_url')
    op.drop_column('recipes', 'user_id')
    op.drop_index(op.f('ix_extraction_cache_expires_at'), table_name='extraction_cache')
    op.drop_table('extraction_cache')
    # ### end Alembic commands ###
