"""add_auth_fields

Revision ID: d03ef81d7de7
Revises: cbb4e747c986
Create Date: 2026-01-02 15:16:47.132335

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d03ef81d7de7"
down_revision: Union[str, Sequence[str], None] = "cbb4e747c986"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("auth_provider", sa.String(), nullable=True))
    op.execute("UPDATE users SET auth_provider = 'email' WHERE auth_provider IS NULL")
    op.alter_column("users", "auth_provider", nullable=False)
    op.add_column("users", sa.Column("provider_id", sa.String(), nullable=True))
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("users", "provider_id")
    op.drop_column("users", "auth_provider")
    # ### end Alembic commands ###
